### ISSUE TITLE
Schematic cosmetics

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/BaseMod#11]
- [x] On DAC_channel: dicrete-elemet -> discrete-element
- [x] J22, IC14, IC6 mark unconnected lines with NC

**Comment by marmeladapk** [comment]
Power estimation:
 - [x] IC24 (8 mA) could be added to 2V5
 - [x] LTC2324 has 31,5 mA max on 2V5 and 36,5 mA max on 5V0
 - How was ERA-3XSM current counted?

**Comment by gkasprow** [comment]
I added LVDS current to LTC2324.
ERA-4XSM+ current estimation was wrong. It should be 4x65mA

**Comment by gkasprow** [comment]
Wrong PN for power amplifier was used.
