### ISSUE TITLE
InAmp power

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/BaseMod#26]
Currently, the InAmps are powered from the filtered (SMPS) P12V0A and NV12V0A lines. I'm a little worried that this will be problematic for the higher InAmp gain settings (smaller input signals).

What about adding P/N 11V5 rails for the InAmps (we may be able to use the existing P11V5 rail, but I'd be worried about leakage from the amplifier/DAC RF onto the supply rail getting rectified in OpAmps leading to DC offsets)?

For small common-mode voltages the AD8253 will still be able to hit +-10V at 11V5 supply, although it's more comfortable at 12V supplies.

**Comment by gkasprow** [comment]
added dedicated LDOs for both rails
