### ISSUE TITLE
Channel zero has lower amplitude

### ISSUE THREAD

**Issue by marmeladapk** [sinara-hw/BaseMod#30]
![obraz](https://user-images.githubusercontent.com/24512604/72448368-2b1bb380-37b7-11ea-8dec-e43bbdeb61d6.png)

Yellow: SMA output from channel 0
Blue: SMA output from channel 1
Violet: Probe of channel 0
Green: Probe of channel 1

Channels were probed on R95, so before amplifier and after filter and balun. It seems that CH0 has higher amplitude initially, but then it gets distorted.

It's consistent on all basemods that we tried.

**Comment by marmeladapk** [comment]
![obraz](https://user-images.githubusercontent.com/24512604/72455354-e72eab80-37c2-11ea-83f5-60fbb0d65551.png)

Measuring on DAC output, negative lines.

**Comment by gkasprow** [comment]
Try it with lower frequency. Try to swap the scope probes between channels.

**Comment by marmeladapk** [comment]
I'll try on sine generator from @sbourdeauducq, but I'll need to swap channels in JCDG.

**Comment by marmeladapk** [comment]
Output from modified testmod (yellow, blue - dac ch0; pink, green - dac ch2), averaging from 32 triggers
![obraz](https://user-images.githubusercontent.com/24512604/72739291-a8726a00-3ba3-11ea-8de3-699547dd0e86.png)

I removed baluns and connected SMA directly to +- lines.

Differential signal Ch0:
![obraz](https://user-images.githubusercontent.com/24512604/72739726-888f7600-3ba4-11ea-97ad-41c6cb479d4b.png)

Differential signal Ch2:
![obraz](https://user-images.githubusercontent.com/24512604/72739895-e8861c80-3ba4-11ea-8ad8-33960627a3c3.png)

Waveforms compared (red: DAC channel 0 differential, white: DAC channel 2 differential)
![obraz](https://user-images.githubusercontent.com/24512604/72740374-d5278100-3ba5-11ea-9662-ab1a9ddd68f5.png)

So there's a slight difference, but nothing as drastic as we saw on Basemod. Those small differences could be due to solder joints, slightly longer cables which were used to connect pads etc. I'd say that the problem is on Basemod. Thoughts @gkasprow ?

Here's the same measurement on ARTIQ (but 50 MHz instead of 240 MHz), all channels get sine wave, phase difference is due to gateware. Same situation.

![obraz](https://user-images.githubusercontent.com/24512604/72741389-d063cc80-3ba7-11ea-969d-2337cc21dce0.png)

**Comment by sbourdeauducq** [comment]
> Here's the same measurement on ARTIQ (but 50 MHz instead of 240 MHz)

If you upgrade Vivado, you should be able to get 240MHz out of ARTIQ using SAWG. I was able to get SAWG sine output on my board.

**Comment by marmeladapk** [comment]
Yellow: Channel0_N Blue: Channel0_P Pink: Channel1_N Green: Channel1_P, measured at TR1 pads (6 and 4)
![obraz](https://user-images.githubusercontent.com/24512604/72892696-741fba80-3d17-11ea-8619-1d0d424dac81.png)

**Comment by gkasprow** [comment]
I looks loke asymetrically driven balun. Check if there is connection between dac and balun on both p and n wires.

Pozdrawiam,
G.Kasprowicz

________________________________

**Comment by marmeladapk** [comment]
Channel 0 (averaging from 32 triggers) measured at capacitor pads (so directly from on DAC output with C37 and C46 removed)
![obraz](https://user-images.githubusercontent.com/24512604/72897857-2e68ef00-3d23-11ea-8926-1d5063b8883c.png)

**Comment by gkasprow** [comment]
How it compares with other channels?

Pozdrawiam,
G.Kasprowicz

________________________________

**Comment by marmeladapk** [comment]
This is asymetrically driven balun: only _N (yellow) is driven and _P (blue) is measured:
![obraz](https://user-images.githubusercontent.com/24512604/72899257-e5666a00-3d25-11ea-8d39-b7ab15c8394f.png)

**Comment by gkasprow** [comment]
this would explain the issue. maybe connector pad assignment is wrong?

**Comment by marmeladapk** [comment]
@gkasprow In the previous screenshot I left one of capacitors unpopulated (on _P line).

**Comment by marmeladapk** [comment]
I replaced C46 and C37, still _P line is weaker.

**Comment by marmeladapk** [comment]
I removed R41 - jumper after balun on channel 0 so channel 0 is not loaded.
yellow blue - ch0; pink green - ch1 (not modified, for reference)
![obraz](https://user-images.githubusercontent.com/24512604/72907786-c91df980-3d34-11ea-8119-b1c8a947e910.png)

So the effect persists.

Ed: Removing C44 didn't help either.

Ed2: I removed R41 on reference channel, it still is symetric.

**Comment by marmeladapk** [comment]
Thought for later: I can't see anything special about layer of channel 0. Since it's skewed on all boards that we tried perhaps the PCB has some defect?

The effect seems to be caused by balun (currently its output is disconnected and signal from DAC looked fine when balun was disconnected). It's not caused by C37 and C46, I replaced them. Removing C44 didn't help. Maybe pads under balun have some resistive connection to something?

**Comment by gkasprow** [comment]
We can check it with VNA tomorrow.

**Comment by marmeladapk** [comment]
After amplifier:

![tek00000](https://user-images.githubusercontent.com/24512604/73277736-dfbbc900-41ea-11ea-8c54-f565a5f736ef.png)

**Comment by marmeladapk** [comment]
Swapping amplifiers didn't change the situation, chan 0 is still distorted.

**Comment by gkasprow** [comment]
But surprisingly, the signal from balun, routed to the SMA with a piece of the cable looks OK, it has the same amplitude on both channels.

**Comment by marmeladapk** [comment]
@jbqubit We forgot to write about this, but Basemods from another supplier don't exhibit this issue. @atcher0 has new screenshots.
