### ISSUE TITLE
BaseMod Photos

### ISSUE THREAD

**Issue by jbqubit** [sinara-hw/BaseMod#31]
For accounting purposes please post high resolution photo of stuffed BaseMod front and back sides. Also post photo showing stuffed PCBs (one photo of array of boards is fine). 

> BaseMod v2.0: print 20 PCBs, stuff 12

**Comment by akaminska** [comment]
1907180PW0007A0108
1907180PW0007A0105
1907180PW0007A0109
1907180PW0007A0115
1907180PW0007A0113
1907180PW0007A0106
1907180PW0007A0110
1907180PW0007A0104
1907180PW0007A0107
1907180PW0007A0114
1907180PW0007A0111
1907180PW0007A0112
![IMG_20191220_130336__01](https://user-images.githubusercontent.com/45766037/78687874-ea829080-78f4-11ea-954b-1434b29671a9.jpg)
![IMG_20191220_130442__01](https://user-images.githubusercontent.com/45766037/78687912-f2dacb80-78f4-11ea-92ce-3b0bcb9742d5.jpg)

**Comment by akaminska** [comment]
Unpopulated PCBs
![IMG_2556](https://user-images.githubusercontent.com/45766037/78688055-2289d380-78f5-11ea-893c-655cdcb87ec8.jpg)
![IMG_2557](https://user-images.githubusercontent.com/45766037/78688068-24539700-78f5-11ea-8833-0d21492f6fb2.jpg)

**Comment by jbqubit** [comment]
Thank you!
