### ISSUE TITLE
fp connector

### ISSUE THREAD

**Issue by hartytp** [sinara-hw/BaseMod#9]
if were converging on MCX as our choice elsewhere then let's use that for the analog inputs, assuming there is enough space (we're currently using MMCX which is a little smaller and less robust).

**Comment by marmeladapk** [comment]
@gkasprow Currently there are MMCX in schematics.

**Comment by gkasprow** [comment]
True, I didn't implement all the fixes yet.

**Comment by gkasprow** [comment]
no way to fit both SMA and MCX.
